version: '3.1'

services:

  secret-santa-tg-bot:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: prod
    image: beer13/secret-santa-tg-bot:latest
    container_name: secret-santa-tg-bot
    restart: always
    env_file:
      - ../.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ../database:/data/db
    env_file:
      - ../.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ../.env