version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ../database:/data/db
    ports:
      - 27017:27017
    env_file:
      - ../.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ../.env